const data={english:[..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"].map((l,i)=>[l,`${l} for ${['Apple','Ball','Cat','Dog','Elephant','Fish','Grapes','House','Ice cream','Juice','Kite','Lion','Mango','Nest','Orange','Parrot','Queen','Rabbit','Sun','Tiger','Umbrella','Van','Watermelon','Xylophone','Yak','Zebra'][i]}`,['🍎','⚽','🐱','🐶','🐘','🐟','🍇','🏠','🍦','🧃','🪁','🦁','🥭','🪺','🍊','🦜','👑','🐰','☀️','🐯','☂️','🚐','🍉','🎵','🐃','🦓'][i]]),numbers:[...Array(20)].map((_,i)=>[String(i+1),`${i+1} ${['One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen','Twenty'][i]}`,['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','1️⃣1️⃣','1️⃣2️⃣','1️⃣3️⃣','1️⃣4️⃣','1️⃣5️⃣','1️⃣6️⃣','1️⃣7️⃣','1️⃣8️⃣','1️⃣9️⃣','2️⃣0️⃣'][i]]),hindi:[['अ','अनार','🍎'],['आ','आम','🥭'],['इ','इमली','🌿'],['ई','ईख','🌱'],['उ','उल्लू','🦉'],['ऊ','ऊन','🧶'],['ए','एड़ी','🦶'],['ऐ','ऐनक','👓'],['ओ','ओखली','🥣'],['औ','औरत','👩'],['क','कबूतर','🕊️'],['ख','खरगोश','🐇'],['ग','गमला','🪴'],['घ','घर','🏠'],['च','चम्मच','🥄'],['छ','छाता','☂️'],['ज','जहाज','🚢'],['झ','झंडा','🚩'],['ट','टमाटर','🍅'],['ठ','ठेला','🛒'],['ड','डमरू','🥁'],['ढ','ढक्कन','🫙'],['त','तरबूज','🍉'],['थ','थर्मस','🧴'],['द','दरवाज़ा','🚪'],['ध','धनुष','🏹'],['न','नल','🚰'],['प','पतंग','🪁'],['फ','फल','🍊'],['ब','बकरी','🐐'],['भ','भालू','🐻'],['म','मछली','🐟'],['य','यज्ञ','🔥'],['र','रथ','🛺'],['ल','लट्टू','🪀'],['व','वन','🌳'],['श','शेर','🦁'],['ष','षट्कोण','⬡'],['स','साँप','🐍'],['ह','हाथी','🐘']],shapes:[['○','Circle','⚪'],['□','Square','⬜'],['△','Triangle','🔺'],['☆','Star','⭐'],['◇','Diamond','💎'],['♥','Heart','❤️']]};
const labels={english:'English',numbers:'Numbers',hindi:'हिंदी',shapes:'Shapes'};let mode='english',index=0,drawn=0,drawing=false,points=[];const $=id=>document.getElementById(id),canvas=$('traceCanvas'),ctx=canvas.getContext('2d');let voices=[];
function loadVoices(){voices='speechSynthesis'in window?speechSynthesis.getVoices():[]}if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}function pickVoice(lang){const p=lang.split('-')[0].toLowerCase();return voices.find(v=>v.lang.toLowerCase()===lang.toLowerCase())||voices.find(v=>v.lang.toLowerCase().startsWith(p))}
function speak(text,lang='en-US',rate=.78){if(window.TTS){try{window.TTS.speak({text,locale:lang,rate}).catch(()=>browserSpeak(text,lang,rate));return}catch(e){}}browserSpeak(text,lang,rate)}function browserSpeak(text,lang,rate){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=rate;u.pitch=1.12;const v=pickVoice(lang);if(v)u.voice=v;speechSynthesis.speak(u)}
function lessonSpeech(){const x=data[mode][index];if(mode==='english')speak(`${x[0]}. ${x[1]}`);else if(mode==='numbers')speak(`${x[0]}. ${x[1].slice(x[0].length+1)}`);else if(mode==='hindi')speak(`${x[0]} से ${x[1]}`,'hi-IN',.72);else speak(x[1])}function tone(f=660,d=.09){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d);setTimeout(()=>a.close(),d*1000+30)}function successSound(){tone(660,.1);setTimeout(()=>tone(880,.12),110);setTimeout(()=>tone(1047,.16),240)}function errorSound(){tone(240,.12);setTimeout(()=>tone(190,.16),130)}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);ctx.lineCap='round';ctx.lineJoin='round'}function clearTrace(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);drawn=0;points=[]}
function completed(){return JSON.parse(localStorage.getItem(`kids-seekho-${mode}`)||'[]')}function completedFor(m){return JSON.parse(localStorage.getItem(`kids-seekho-${m}`)||'[]')}function updateHomeProgress(){let total=0,done=0;Object.keys(data).forEach(m=>{total+=data[m].length;done+=completedFor(m).length});$('progressText').textContent=`${done} / ${total}`;$('progressBar').style.width=`${total?done/total*100:0}%`;$('progressLabel').textContent=done?`शानदार! ${done} lessons पूरे ⭐`:'अभी शुरुआत करें 🌟'}
function render(){const x=data[mode][index];$('modeLabel').textContent=labels[mode];$('counter').textContent=`${index+1} / ${data[mode].length}`;$('letter').textContent=x[0];$('guide').textContent=x[0];$('picture').textContent=x[2]||'✨';$('word').textContent=mode==='english'?`${x[0]} — ${x[1].replace(/^[A-Z] for /,'')}`:x[1];$('hint').textContent='पहले सुनो, फिर हल्के अक्षर के रास्ते पर उंगली चलाओ ✨';clearTrace();resizeCanvas();setTimeout(lessonSpeech,220)}function openMode(m){mode=m;index=0;$('homeScreen').classList.remove('active');$('learnScreen').classList.add('active');tone(620,.08);render()}function home(){updateHomeProgress();$('learnScreen').classList.remove('active');$('homeScreen').classList.add('active');if(window.TTS){try{window.TTS.silence()}catch(e){}}if('speechSynthesis'in window)speechSynthesis.cancel()}function next(){index=index<data[mode].length-1?index+1:0;render()}
function pos(e){const r=canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:t.clientX-r.left,y:t.clientY-r.top}}function start(e){e.preventDefault();drawing=true;const p=pos(e);points.push(p);ctx.beginPath();ctx.moveTo(p.x,p.y);tone(520,.045)}function move(e){if(!drawing)return;e.preventDefault();const p=pos(e);points.push(p);ctx.lineTo(p.x,p.y);ctx.strokeStyle='#6c5ce7';ctx.lineWidth=10;ctx.stroke();drawn++}function end(){drawing=false}
canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end);
function guideScore(){if(points.length<25)return 0;const r=canvas.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height),g=$('guide'),cs=getComputedStyle(g),off=document.createElement('canvas');off.width=Math.ceil(w);off.height=Math.ceil(h);const oc=off.getContext('2d');oc.font=`${cs.fontWeight} ${cs.fontSize} ${cs.fontFamily}`;oc.textAlign='center';oc.textBaseline='middle';oc.fillStyle='#000';oc.fillText(g.textContent,w/2,h/2);const img=oc.getImageData(0,0,off.width,off.height).data;let good=0;const radius=18;for(const p of points){let hit=false;const x=Math.round(p.x),y=Math.round(p.y);for(let yy=Math.max(0,y-radius);yy<=Math.min(off.height-1,y+radius)&&!hit;yy+=3)for(let xx=Math.max(0,x-radius);xx<=Math.min(off.width-1,x+radius);xx+=3){if(img[(yy*off.width+xx)*4+3]>30){hit=true;break}}if(hit)good++}return good/points.length}
function check(){if(drawn<25){$('hint').textContent='थोड़ा और लिखो 👆 अक्षर पूरा बनाओ!';errorSound();setTimeout(()=>speak('अक्षर पूरा लिखो, फिर कोशिश करो।','hi-IN',.78),120);return}const score=guideScore();if(score<.58){$('hint').textContent=score<.3?'अक्षर के हल्के रास्ते पर उंगली चलाओ 👆':'थोड़ा ध्यान से लिखो। हल्के अक्षर के ऊपर लिखने की कोशिश करो ✨';errorSound();setTimeout(()=>speak('कोई बात नहीं। फिर से कोशिश करो।','hi-IN',.78),120);return}let key=`kids-seekho-${mode}`,done=completedFor(mode);if(!done.includes(index)){done.push(index);localStorage.setItem(key,JSON.stringify(done))}$('hint').textContent='शाबाश! ⭐';successSound();setTimeout(()=>speak(mode==='hindi'?'बहुत बढ़िया! तुमने बहुत अच्छा लिखा।':'Great job! You did it!','en-US',.82),280);updateHomeProgress();$('success').classList.add('show');$('success').setAttribute('aria-hidden','false')}
$('successNext').onclick=()=>{$('success').classList.remove('show');$('success').setAttribute('aria-hidden','true');next()};$('checkBtn').onclick=check;$('clearBtn').onclick=()=>{clearTrace();tone(430,.06);$('hint').textContent='फिर से कोशिश करो ✨'};$('nextBtn').onclick=next;$('backBtn').onclick=home;$('homeBtn').onclick=home;$('speakBtn').onclick=()=>{lessonSpeech();tone(760,.06)};$('soundBtn').onclick=()=>speak('Kids Seekho','en-US',.78);document.querySelectorAll('.category').forEach(b=>b.onclick=()=>openMode(b.dataset.mode));window.addEventListener('resize',()=>{if($('learnScreen').classList.contains('active')){clearTrace();resizeCanvas()}});updateHomeProgress();resizeCanvas();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));

/* Mother voice recordings for English A/B/C */
const MOM_EN_AUDIO=['audio/en/01.mp3','audio/en/02.mp3','audio/en/03.mp3'];
let momPlayer=null;
const originalLessonSpeech=lessonSpeech;
function playMomVoice(){
  if(mode!=='english'||index>2)return false;
  try{
    if(!momPlayer)momPlayer=new Audio();
    momPlayer.pause();momPlayer.currentTime=0;momPlayer.src=MOM_EN_AUDIO[index];
    const p=momPlayer.play();
    if(p&&p.catch)p.catch(()=>{});
    return true;
  }catch(e){return false}
}
lessonSpeech=function(){if(!playMomVoice())originalLessonSpeech()};
