const data={
 english:[..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"].map((l,i)=>[l,`${l} for ${['Apple','Ball','Cat','Dog','Elephant','Fish','Grapes','House','Ice cream','Juice','Kite','Lion','Mango','Nest','Orange','Parrot','Queen','Rabbit','Sun','Tiger','Umbrella','Van','Watermelon','Xylophone','Yak','Zebra'][i]}`,['🍎','⚽','🐱','🐶','🐘','🐟','🍇','🏠','🍦','🧃','🪁','🦁','🥭','🪺','🍊','🦜','👑','🐰','☀️','🐯','☂️','🚐','🍉','🎵','🐃','🦓'][i]]),
 numbers:[...Array(20)].map((_,i)=>[String(i+1),`${i+1} ${['One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen','Twenty'][i]}`,['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','1️⃣1️⃣','1️⃣2️⃣','1️⃣3️⃣','1️⃣4️⃣','1️⃣5️⃣','1️⃣6️⃣','1️⃣7️⃣','1️⃣8️⃣','1️⃣9️⃣','2️⃣0️⃣'][i]]),
 hindi:[['अ','अनार','🍎'],['आ','आम','🥭'],['इ','इमली','🌿'],['ई','ईख','🌱'],['उ','उल्लू','🦉'],['ऊ','ऊन','🧶'],['ए','एड़ी','🦶'],['ऐ','ऐनक','👓'],['ओ','ओखली','🥣'],['औ','औरत','👩'],['क','कबूतर','🕊️'],['ख','खरगोश','🐇'],['ग','गमला','🪴'],['घ','घर','🏠'],['च','चम्मच','🥄'],['छ','छाता','☂️'],['ज','जहाज','🚢'],['झ','झंडा','🚩'],['ट','टमाटर','🍅'],['ठ','ठेला','🛒'],['ड','डमरू','🥁'],['ढ','ढक्कन','🫙'],['त','तरबूज','🍉'],['थ','थर्मस','🧴'],['द','दरवाज़ा','🚪'],['ध','धनुष','🏹'],['न','नल','🚰'],['प','पतंग','🪁'],['फ','फल','🍊'],['ब','बकरी','🐐'],['भ','भालू','🐻'],['म','मछली','🐟'],['य','यज्ञ','🔥'],['र','रथ','🛺'],['ल','लट्टू','🪀'],['व','वन','🌳'],['श','शेर','🦁'],['ष','षट्कोण','⬡'],['स','साँप','🐍'],['ह','हाथी','🐘']],
 shapes:[['○','Circle','⚪'],['□','Square','⬜'],['△','Triangle','🔺'],['☆','Star','⭐'],['◇','Diamond','💎'],['♥','Heart','❤️']]
};
const labels={english:'English',numbers:'Numbers',hindi:'हिंदी',shapes:'Shapes'};
let mode='english',index=0,drawing=false,points=[],autoTimer=null,checking=false;
const $=id=>document.getElementById(id),canvas=$('traceCanvas'),ctx=canvas.getContext('2d');
let voices=[];
function loadVoices(){voices='speechSynthesis'in window?speechSynthesis.getVoices():[]}if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}
function pickVoice(lang){const p=lang.split('-')[0].toLowerCase();return voices.find(v=>v.lang.toLowerCase()===lang.toLowerCase())||voices.find(v=>v.lang.toLowerCase().startsWith(p))}
function browserSpeak(text,lang,rate){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=rate;u.pitch=1.12;const v=pickVoice(lang);if(v)u.voice=v;speechSynthesis.speak(u)}
function speak(text,lang='en-US',rate=.78){if(window.TTS){try{const r=window.TTS.speak({text,locale:lang,rate});if(r&&r.catch)r.catch(()=>browserSpeak(text,lang,rate));return}catch(e){}}browserSpeak(text,lang,rate)}
const AUDIO_DB='KidsSeekhoAudioDB',AUDIO_STORE='recordings';let audioDb=null,customPlayer=null;
function openAudioDb(){return new Promise((resolve,reject)=>{if(audioDb)return resolve(audioDb);const r=indexedDB.open(AUDIO_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(AUDIO_STORE))r.result.createObjectStore(AUDIO_STORE)};r.onsuccess=()=>{audioDb=r.result;resolve(audioDb)};r.onerror=()=>reject(r.error)})}
function audioKey(m,i){return`${m}-${i}`}
async function getLocalAudio(key){try{const db=await openAudioDb();return await new Promise((resolve,reject)=>{const r=db.transaction(AUDIO_STORE).objectStore(AUDIO_STORE).get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}catch(e){return null}}
async function saveLocalAudio(key,file){const db=await openAudioDb();return new Promise((resolve,reject)=>{const t=db.transaction(AUDIO_STORE,'readwrite');t.objectStore(AUDIO_STORE).put({blob:file,name:file.name,type:file.type,updated:Date.now()},key);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
const MOM_EN_AUDIO=['audio/en/01.mp3','audio/en/02.mp3','audio/en/03.mp3'];
async function lessonSpeech(){const saved=await getLocalAudio(audioKey(mode,index));if(saved&&saved.blob){try{if(customPlayer)customPlayer.pause();customPlayer=new Audio(URL.createObjectURL(saved.blob));await customPlayer.play();return}catch(e){}}if(mode==='english'&&index<3){try{if(customPlayer)customPlayer.pause();customPlayer=new Audio(MOM_EN_AUDIO[index]);await customPlayer.play();return}catch(e){}}const x=data[mode][index];if(mode==='english')speak(`${x[0]}. ${x[1]}`);else if(mode==='numbers')speak(`${x[0]}. ${x[1].slice(x[0].length+1)}`);else if(mode==='hindi')speak(`${x[0]} से ${x[1]}`,'hi-IN',.72);else speak(x[1])}
function tone(f=660,d=.09){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;try{const a=new A(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d);setTimeout(()=>a.close(),d*1000+50)}catch(e){}}
function errorSound(){tone(180,.16);setTimeout(()=>tone(125,.2),150)}
function rewardSound(){tone(523,.11);setTimeout(()=>tone(659,.11),100);setTimeout(()=>tone(784,.13),200);setTimeout(()=>tone(1047,.22),330);setTimeout(()=>tone(1319,.28),500)}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);ctx.lineCap='round';ctx.lineJoin='round'}
function clearTrace(){clearTimeout(autoTimer);checking=false;const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);points=[]}
function completedFor(m){try{return JSON.parse(localStorage.getItem(`kids-seekho-${m}`)||'[]')}catch(e){return[]}}
function updateHomeProgress(){let total=0,done=0;Object.keys(data).forEach(m=>{total+=data[m].length;done+=completedFor(m).length});$('progressText').textContent=`${done} / ${total}`;$('progressBar').style.width=`${total?done/total*100:0}%`;$('progressLabel').textContent=done?`शानदार! ${done} lessons पूरे ⭐`:'अभी शुरुआत करें 🌟'}
function hideFeedback(){['errorMark','rewardMark'].forEach(id=>$(id).classList.remove('show'))}
function showError(){hideFeedback();$('errorMark').classList.add('show');setTimeout(()=>hideFeedback(),900)}
function showReward(){hideFeedback();$('rewardMark').classList.add('show');setTimeout(()=>hideFeedback(),900)}
function render(){const x=data[mode][index];$('modeLabel').textContent=labels[mode];$('counter').textContent=`${index+1} / ${data[mode].length}`;$('letter').textContent=x[0];$('guide').textContent=x[0];$('picture').textContent=x[2]||'✨';$('word').textContent=mode==='english'?`${x[0]} — ${x[1].replace(/^[A-Z] for /,'')}`:x[1];$('hint').textContent='पहले सुनो, फिर हल्के अक्षर के रास्ते पर उंगली चलाओ ✨';clearTrace();hideFeedback();resizeCanvas();setTimeout(lessonSpeech,220)}
function openMode(m){mode=m;index=0;$('homeScreen').classList.remove('active');$('learnScreen').classList.add('active');tone(620,.08);render()}
function home(){clearTimeout(autoTimer);updateHomeProgress();$('learnScreen').classList.remove('active');$('homeScreen').classList.add('active');if(window.TTS)try{window.TTS.silence()}catch(e){}if('speechSynthesis'in window)speechSynthesis.cancel();if(customPlayer)customPlayer.pause()}
function next(){index=index<data[mode].length-1?index+1:0;render()}
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function start(e){if(checking)return;e.preventDefault();drawing=true;const p=pos(e);points.push(p);ctx.beginPath();ctx.moveTo(p.x,p.y)}
function move(e){if(!drawing||checking)return;e.preventDefault();const p=pos(e);points.push(p);ctx.lineTo(p.x,p.y);ctx.strokeStyle='#6c5ce7';ctx.lineWidth=10;ctx.stroke()}
function end(){if(!drawing)return;drawing=false;clearTimeout(autoTimer);autoTimer=setTimeout(autoCheck,850)}
canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);canvas.style.touchAction='none';
function makeGuideMask(){const r=canvas.getBoundingClientRect(),w=Math.max(1,Math.floor(r.width)),h=Math.max(1,Math.floor(r.height)),off=document.createElement('canvas');off.width=w;off.height=h;const oc=off.getContext('2d'),g=$('guide'),cs=getComputedStyle(g);oc.font=`${cs.fontWeight} ${cs.fontSize} ${cs.fontFamily}`;oc.textAlign='center';oc.textBaseline='middle';oc.fillStyle='#000';oc.fillText(g.textContent,w/2,h/2);return{img:oc.getImageData(0,0,w,h).data,w,h}}
function traceScore(){if(points.length<30)return{hit:0,coverage:0};const {img,w,h}=makeGuideMask(),radius=20;let hit=0;for(const p of points){let ok=false,x=Math.round(p.x),y=Math.round(p.y);for(let yy=Math.max(0,y-radius);yy<=Math.min(h-1,y+radius)&&!ok;yy+=3)for(let xx=Math.max(0,x-radius);xx<=Math.min(w-1,x+radius);xx+=3){if(img[(yy*w+xx)*4+3]>30){ok=true;break}}if(ok)hit++}let guideCount=0,covered=0;const step=5;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){if(img[(y*w+x)*4+3]>30){guideCount++;let near=false;for(let j=0;j<points.length;j+=Math.max(1,Math.floor(points.length/300))){const dx=points[j].x-x,dy=points[j].y-y;if(dx*dx+dy*dy<=radius*radius){near=true;break}}if(near)covered++}}return{hit:hit/points.length,coverage:guideCount?covered/guideCount:0}}
function autoCheck(){if(checking)return;if(points.length<30){if(points.length>0){$('hint').textContent='✍️ अक्षर पूरा करके उंगली हटाओ…';errorSound()}return}checking=true;const s=traceScore(),pass=s.hit>=.60&&s.coverage>=.28;if(!pass){$('hint').textContent=s.hit<.45||s.coverage<.18?'❌ अक्षर सही रास्ते पर नहीं लिखा। फिर से कोशिश करो।':'❌ थोड़ा और सही लिखो। हल्के अक्षर के ऊपर उंगली चलाओ ✨';showError();errorSound();setTimeout(()=>speak('कोई बात नहीं। फिर से कोशिश करो।','hi-IN',.78),180);checking=false;return}let done=completedFor(mode);if(!done.includes(index)){done.push(index);localStorage.setItem(`kids-seekho-${mode}`,JSON.stringify(done))}$('hint').textContent='⭐ शाबाश! बिल्कुल सही!';showReward();rewardSound();setTimeout(()=>speak(mode==='hindi'?'बहुत बढ़िया! तुमने बहुत अच्छा लिखा।':'Great job! You did it!','en-US',.82),250);updateHomeProgress();$('success').classList.add('show');$('success').setAttribute('aria-hidden','false');setTimeout(()=>{$('success').classList.remove('show');$('success').setAttribute('aria-hidden','true');checking=false;next()},1200)}
async function renderAudioList(){const list=$('audioList');list.innerHTML='';for(const m of ['english','hindi','numbers','shapes']){const title=document.createElement('div');title.className='section-title';title.textContent=labels[m];list.appendChild(title);for(let i=0;i<data[m].length;i++){const x=data[m][i],key=audioKey(m,i),saved=await getLocalAudio(key),row=document.createElement('div');row.className='audio-row';const desc=m==='english'?`${x[0]} — ${x[1].replace(/^[A-Z] for /,'')}`:x[1];row.innerHTML=`<div class="audio-letter">${x[0]}</div><div class="audio-info"><b>${desc}</b><small class="audio-status">${saved?'✓ इस फोन में सेव है':'अभी ऑडियो नहीं है'}</small></div><div class="audio-actions"><button class="audio-btn play" ${saved?'':'disabled'}>▶️</button><button class="audio-btn save">📁 चुनें</button><input class="audio-file" type="file" accept="audio/*" hidden></div>`;const play=row.querySelector('.play'),choose=row.querySelector('.save'),input=row.querySelector('.audio-file');play.onclick=async()=>{const a=await getLocalAudio(key);if(!a)return;if(customPlayer)customPlayer.pause();customPlayer=new Audio(URL.createObjectURL(a.blob));customPlayer.play().catch(()=>{})};choose.onclick=()=>input.click();input.onchange=async()=>{const f=input.files&&input.files[0];if(!f)return;await saveLocalAudio(key,f);await renderAudioList()};list.appendChild(row)}}}
$('audioManagerBtn').onclick=async()=>{$('audioManager').classList.add('show');$('audioManager').setAttribute('aria-hidden','false');await renderAudioList()};$('audioClose').onclick=()=>{$('audioManager').classList.remove('show');$('audioManager').setAttribute('aria-hidden','true');if(customPlayer)customPlayer.pause()};$('clearBtn').onclick=()=>{clearTrace();$('hint').textContent='फिर से हल्के अक्षर के रास्ते पर उंगली चलाओ ✨'};$('backBtn').onclick=home;$('homeBtn').onclick=home;$('speakBtn').onclick=()=>lessonSpeech();$('soundBtn').onclick=()=>speak('Kids Seekho','en-US',.78);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>openMode(b.dataset.mode));updateHomeProgress();
window.addEventListener('resize',()=>{if($('learnScreen').classList.contains('active'))resizeCanvas()});
